
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/static
      - ./keys.json:/app/keys.json
    environment:
      - DEBUG=True
      - REDIS_URL=redis://redis:6379/1
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A ANANews worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - DEBUG=True
      - REDIS_URL=redis://redis:6379/1
    depends_on:
      - redis

volumes:
  redis_data:
  static_volume: