# Generated by Django 5.1.6 on 2025-03-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='analysed_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id_one', models.IntegerField()),
                ('news_id_two', models.IntegerField()),
                ('date', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('sentiment', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('top_key_freq', models.JSONField(default=list)),
                ('tokens', models.JSONField(default=list)),
                ('tokens_v2', models.JSONField(default=list)),
                ('entities', models.TextField(blank=True, null=True)),
                ('token_pos', models.TextField(blank=True, null=True)),
                ('photo_link', models.TextField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('news_id_one', 'news_id_two')},
            },
        ),
    ]
