# Generated by Django 5.1.6 on 2025-03-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysed_news',
            name='sentiment',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='analysed_news',
            name='summary',
            field=models.JSONField(default=list),
        ),
    ]
