# Generated by Django 5.1.6 on 2025-03-21 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_system_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system_config',
            name='all_news_category',
        ),
    ]
